# Generated by Django 4.2.7 on 2023-12-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaryapp', '0007_rename_word_chomolokko'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('cookies', models.TextField(verbose_name='Cookies')),
                ('query_word', models.CharField(max_length=255, verbose_name='Search Query')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='User ID')),
                ('device_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Device Type')),
                ('browser_info', models.TextField(blank=True, null=True, verbose_name='Browser Information')),
                ('search_category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Search Category')),
                ('search_results_count', models.IntegerField(blank=True, null=True, verbose_name='Search Results Count')),
                ('search_duration', models.DurationField(blank=True, null=True, verbose_name='Search Duration')),
            ],
        ),
    ]
