# Generated by Django 4.2.7 on 2023-12-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaryapp', '0008_searchlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchlog',
            name='requested_url',
            field=models.URLField(blank=True, null=True, verbose_name='Requested URL'),
        ),
    ]
