# Generated by Django 4.2.7 on 2023-12-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaryapp', '0009_searchlog_requested_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scammer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('cookies', models.TextField(verbose_name='Cookies')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
        ),
    ]
